version: '1'
services:
  microservicio:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - spring.datasource.url=jdbc:oracle:thin:@k5y658kbcmfl1d1c_tp?TNS_ADMIN=/app/oracle_wallet
      - spring.datasource.username=USER_GESTION
      - spring.datasource.password=GestiFullStack123
    restart: always